remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Faraj Arvid's Portfolio
description: Welcome to my website! Feel free to learn more about me and connect.
